#!/usr/bin/env bash
# by SJKoh, CrowdInvestNetwork

HASH=$1

curl --silent 'http://blocks.cinetwork.io/daemon/json_rpc' --data '{"jsonrpc":"2.0","id":"test","method":"f_transaction_json","params":{"hash":"'"$HASH"'"}}' --compressed | jq '.result.tx.extra' | xxd -r -p













